/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include "MCAL/mcal_rcc.h"
#include "MCAL/mcal_gpio.h"

extern void initialise_monitor_handles(void);

int main(void)
{
	initialise_monitor_handles();

	rcc_gpioPortClkEnable(GPIOA);
	gpioA_setPinConf(0, OUTPUT_10MHZ, GP_OUT_PUSH_PULL);
	gpioA_setPinConf(1, OUTPUT_10MHZ, GP_OUT_PUSH_PULL);

	printf("Turning on led number 1\r\n");
	gpioA_setPinState(0, HIGH);
	printf("Turning on led number 2\r\n");
	gpioA_setPinState(1, HIGH);

	/* Loop forever */
	for(;;);
}
